### ISSUE TITLE
Use of NoSQL/ SQL DB

### ISSUE THREAD

**Issue by AdityaMore7000** [piyushhagarwal/DBMS_23-24#2]
Hi Peeyush, while going through your code I realised it is using MongoDB, isn't it a requirement to use relational database for a project? Or can any database be used??

**Comment by piyushhagarwal** [comment]
Hey Aditya! 
I chose MongoDB, a NoSQL database, because my data is pretty unstructured. As you've probably noticed from the project, I'm dealing with arrays of questions and answers, and the array sizes can vary.

**Comment by AdityaMore7000** [comment]
Ok, so it means it is not necessary to use relational db for dbms project, right?

**Comment by piyushhagarwal** [comment]
Yes you can use either SQL or MongoDB for the project.

**Comment by AdityaMore7000** [comment]
Ok, thanks.
